#!/usr/bin/env bash

set -o errexit
set -o pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker compose build
  docker compose run ${TTY} "${@}"
  docker compose down
}

# -----------------------------------------------------------------------------

function flush_redis_cache {
  _dc redis-server redis-cli FLUSHALL
}

function cmd {
  _dc web "${@}"
}

function manage {
  cmd python3 manage.py "${@}"
}

function collectstatic {
  cmd python manage.py collectstatic --no-input
}

function migrate {
  cmd python manage.py migrate
}

function test {
  echo "Running tests"
  cmd python manage.py test
}

function reset_db {
  manage reset_db -c --noinput
  manage makemigrations
  migrate
  manage create_superuser
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"
  
  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"