# Generated by Django 4.2.11 on 2024-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_usage_sharecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='duration',
            field=models.FloatField(help_text='Duration in seconds'),
        ),
    ]
