# Generated by Django 4.2.11 on 2024-04-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_charge_paymentstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge',
            new_name='Payment',
        ),
    ]
