# Generated by Django 4.2.11 on 2024-04-21 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='usage',
        ),
        migrations.AddField(
            model_name='usage',
            name='payment_status',
            field=models.CharField(default='unpaid', help_text='Payment status: unpaid, pending, paid', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_usages',
            field=models.ManyToManyField(related_name='transactions', to='translation.usage'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
