# Generated by Django 4.2.11 on 2024-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_transaction_remove_paymentstatus_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecode',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
