# Generated by Django 4.2.11 on 2024-04-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_alter_sharecode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
