# Generated by Django 4.2.11 on 2024-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0010_hourlypricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(choices=[('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-250 employees)'), ('large', 'Large (251+ employees)')], max_length=6)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
