# Generated by Django 4.2.11 on 2024-07-23 01:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
