# Generated by Django 4.2.11 on 2024-07-23 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0012_transcriptrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='transcriptrecord',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
