# Generated by Django 4.2.11 on 2024-07-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0013_remove_transcriptrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptrecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
